### ISSUE TITLE
This one?

### ISSUE THREAD

**Issue by KingNelx** [dxp10/player#1]

**Comment by dxp10** [comment]
Yes

**Comment by KingNelx** [comment]
visual element 6/10. Got to fix the typography and the contrast, you can make it lighter (top bar) . Maybe putting some gradient color will be a good idea too. Btw nice work cool.

**Comment by SaruelDustiness** [comment]
It has a nice design that remembers me of some apps I used to have on my phone (I miss them so much, but now all of them have ads) but the color choice is where you can improve like the friend here said. Overall it is a nice project, I'll wait to see how it'll get done.

**Comment by KingNelx** [comment]
Update us bro if you finally edit it.
